DROP TABLE IF EXISTS focus_sessions CASCADE;
DROP TABLE IF EXISTS houses CASCADE;
DROP TABLE IF EXISTS pets CASCADE;
DROP TABLE IF EXISTS porch_dropoffs CASCADE;
DROP TABLE IF EXISTS partnerships CASCADE;
DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS users CASCADE;
